- name: Get metric-storage-prometheus-endpoint secret values
  ansible.builtin.shell: |
    oc get secret metric-storage-prometheus-endpoint -n openstack -o json \
    | jq -r '.data | to_entries[] | "\(.key)=\(.value|@base64d)"'
  register: secret_output
  changed_when: false

- name: Show secret decoded values
  ansible.builtin.debug:
    var: secret_output.stdout_lines

- name: Assert secret contains expected values
  ansible.builtin.assert:
    that:
      - "'ca_key=ca.crt' in secret_output.stdout_lines"
      - "'ca_secret=cert-metric-storage-prometheus-svc' in secret_output.stdout_lines"
      - "'host=metric-storage-prometheus.openstack.svc' in secret_output.stdout_lines"
      - "'port=9090' in secret_output.stdout_lines"
    fail_msg: "Secret metric-storage-prometheus-endpoint is missing required values"
    success_msg: "Secret metric-storage-prometheus-endpoint contains all required values"
