[DEFAULT]
debug=True

[prometheus]
host = localhost
port = 9090
use_tls = {{ .PrometheusTLS }}
project_label_name = project

[keystone_authtoken]
www_authenticate_uri = {{ .KeystoneInternalURL }}
auth_url = {{ .KeystoneInternalURL }}
interface = internal
auth_type = password
username = {{ .ServiceUser }}
password = {{ .ServicePassword }}
user_domain_name = Default
project_name = service
project_domain_name = Default
service_token_roles_required = True
