# permissions for end users to edit ceilometercomputes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ceilometercompute-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: telemetry-operator
    app.kubernetes.io/part-of: telemetry-operator
    app.kubernetes.io/managed-by: kustomize
  name: ceilometercompute-editor-role
rules:
- apiGroups:
  - telemetry.openstack.org
  resources:
  - ceilometercomputes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - telemetry.openstack.org
  resources:
  - ceilometercomputes/status
  verbs:
  - get
