# permissions for end users to view telemetries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telemetry-viewer-role
rules:
- apiGroups:
  - telemetry.openstack.org
  resources:
  - telemetries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - telemetry.openstack.org
  resources:
  - telemetries/status
  verbs:
  - get
