# permissions for end users to edit telemetries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telemetry-editor-role
rules:
- apiGroups:
  - telemetry.openstack.org
  resources:
  - telemetries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - telemetry.openstack.org
  resources:
  - telemetries/status
  verbs:
  - get
