apiVersion: observability.openshift.io/v1                                                                                                                          
kind: ClusterLogForwarder                                                                                                                                          
metadata:
  name: collector-with-cadf-to-loki-audit                                                                                                                          
  namespace: openshift-logging
spec:
  serviceAccount:
    name: collector                                                                                                                                                
  inputs:
  - name: dataplane                                                                                                                                                
    receiver:                                                                                                                                                      
      port: 10514                                                                                                                                                  
      type: syslog                                                                                                                                                 
    type: receiver                                                                                                                                                 
  managementState: Managed
  outputs:                                                                                                                                                         
  - name: default-lokistack                                                                                                                                        
    type: lokiStack
    lokiStack:                                                                                                                                                     
      authentication:
        token:                                                                                                                                                     
          from: serviceAccount                                                                                                                                     
      labelKeys:                                                                                                                                                   
        infrastructure:                                                                                                                                            
          labelKeys:                                                                                                                                               
            - host                                                                                                                                                 
            - appname
      target:                                                                                                                                                      
        name: logging-loki
        namespace: openshift-logging                                                                                                                               
    tls:
      ca:                                                                                                                                                          
        key: service-ca.crt
        configMapName: openshift-service-ca.crt
  - name: audit-lokistack                                                                                                                                          
    type: lokiStack
    lokiStack:                                                                                                                                                     
      authentication:
        token:                                                                                                                                                     
          from: serviceAccount
      target:
        name: logging-loki-audit                                                                                                                                   
        namespace: openshift-logging
    tls:                                                                                                                                                           
      ca:       
        key: service-ca.crt
        configMapName: openshift-service-ca.crt                                                                                                                    
  filters:                                                                                                                                                         
  - name: to-loki-filter                                                                                                                                           
    type: drop                                                                                                                                                     
    drop:                                                                                                                                                          
    - test:                                                                                                                                                        
      - field: .message                                                                                                                                            
        matches: "oslo.messaging.notification"                                                                                                                     
  - name: to-loki-audit-filter
    type: drop                                                                                                                                                     
    drop:       
    - test:                                                                                                                                                        
      - field: .message
        notMatches: "oslo.messaging.notification"
  pipelines:
  - name: to-loki
    inputRefs:
      - application                                                                                                                                                
      - dataplane
    outputRefs:                                                                                                                                                    
      - default-lokistack
    filterRefs:
      - to-loki-filter                                                                                                                                             
  - name: to-loki-audit
    inputRefs:                                                                                                                                                     
      - application
    outputRefs:
      - audit-lokistack
    filterRefs:
      - to-loki-audit-filter
