apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
stringData:
  access_key_id: minio
  access_key_secret: minio123
  bucketnames: loki
  endpoint: http://minio.minio-dev.svc.cluster.local:9000
