- name: Create cinder audit config secret
  ansible.builtin.command: >
    oc create secret generic {{ enable_audit_logging_cinder_secret }}
    -n {{ enable_audit_logging_namespace }}
    --from-file=api-paste.ini={{ role_path }}/files/cinder-api-paste.ini
    --from-file=cinder_api_audit_map.conf={{ role_path }}/files/cinder_api_audit_map.conf

- name: Create glance audit config secret
  ansible.builtin.command: >
    oc create secret generic {{ enable_audit_logging_glance_secret }}
    -n {{ enable_audit_logging_namespace }}
    --from-file=glance-api-paste.ini={{ role_path }}/files/glance-api-paste.ini
    --from-file=glance_api_audit_map.conf={{ role_path }}/files/glance_api_audit_map.conf

- name: Create neutron audit config secret
  ansible.builtin.command: >
    oc create secret generic {{ enable_audit_logging_neutron_secret }}
    -n {{ enable_audit_logging_namespace }}
    --from-file=api-paste.ini={{ role_path }}/files/neutron-api-paste.ini
    --from-file=neutron_api_audit_map.conf={{ role_path }}/files/neutron_api_audit_map.conf
