- name: Create service audit config secrets
  ansible.builtin.include_tasks: create-secrets.yml

- name: Copy controlplane kustomization for audit logging
  ansible.builtin.template:
    src: 90-kustomize-controlplane-audit-logging.yaml.j2
    dest: "{{ cifmw_basedir }}/artifacts/manifests/kustomizations/controlplane/90-kustomize-controlplane-audit-logging.yaml"
  when: not enable_audit_logging_local_apply

- name: Apply kustomization against live OSCP
  ansible.builtin.include_tasks: apply-local.yml
  when: enable_audit_logging_local_apply
