apiVersion: monitoring.rhobs/v1
kind: PrometheusRule
metadata:
  labels:
    service: metricStorage
  name: openstack-observability-services-status
  namespace: openstack
spec:
  groups:
    - name: openstack-observability.services.status
      rules:
      - alert: OpenStackServicesDownWarning
        expr: |
          (
            max(kube_pod_info{created_by_kind=~"ReplicaSet|StatefulSet|OpenStackClient"} * on(uid) group_left(phase) kube_pod_status_phase{phase="Running"}) == 1
          )
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: "RHOSO component down (warning)"
          description: |
            At least one of the RHOSO services is down for more than 10 seconds.
      - alert: OpenStackServicesDownCritical
        expr: |
          (
            max(kube_pod_info{created_by_kind=~"ReplicaSet|StatefulSet|OpenStackClient"} * on(uid) group_left(phase) kube_pod_status_phase{phase="Running"}) == 1
          )
        for: 60s
        labels:
          severity: critical
        annotations:
          summary: "RHOSO component down (critical)"
          description: |
            At least one of the RHOSO services is down for more than 1 minute.
    - name: openstack-observability.scrapeconfig.status
      rules:
      - alert: OpenStackObservabilityDownWarning
        expr: |
          (
            up{job=~"scrapeConfig/openstack/telemetry-(ceilometer|podman-exporter|node-exporter)"} == 0
            or up{service="metric-storage-prometheus"} == 0
          )
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: "Telemetry Operator ScrapeConfig down (warning)"
          description: |
            One of the Telemetry Operator ScrapeConfigs is down for more than 10 seconds.
            Instance: {{ $labels.instance }}
            Job: {{ $labels.job }}
      - alert: OpenStackObservabilityDownCritical
        expr: |
          (
            up{job=~"scrapeConfig/openstack/telemetry-(ceilometer|podman-exporter|node-exporter)"} == 0
            or up{service="metric-storage-prometheus"} == 0
          )
        for: 60s
        labels:
          severity: critical
        annotations:
          summary: "Telemetry Operator ScrapeConfig component down (critical)"
          description: |
            One of the Telemetry Operator ScrapeConfigs is down for more than 1 minute.
            Instance: {{ $labels.instance }}
            Job: {{ $labels.job }}
