---
- name: Execute the default-telemetry scenario
  hosts: "{{ cifmw_target_hook_host | default('localhost')  }}"
  gather_facts: false
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  tasks:
    - name: Execute the default-telemetry scenario
      ansible.builtin.import_role:
        name: default-telemetry
      ignore_errors: true
