---
- name: "Create the kustomization for deploying autoscaling"
  hosts: "{{ cifmw_target_hook_host | default('localhost')  }}"
  gather_facts: false
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  tasks:
    - name: Copy controlplane kustomization
      ansible.builtin.copy:
        dest: "{{ cifmw_basedir }}/artifacts/manifests/kustomizations/controlplane/90-kustomize-controlplane-autoscaling.yaml"
        content: |-
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization
          namespace: openstack
          patches:
          - patch: |-
              apiVersion: core.openstack.org/v1beta1
              kind: OpenStackControlPlane
              metadata:
                name: unused
              spec:
                heat:
                  enabled: true
                telemetry:
                  enabled: true
                  template:
                    metricStorage:
                      enabled: true
                      monitoringStack:
                        alertingEnabled: false
                    autoscaling:
                      enabled: true
                    ceilometer:
                      enabled: true
                      mysqldExporterEnabled: true
            target:
              kind: OpenStackControlPlane
          - patch: |-
              apiVersion: core.openstack.org/v1beta1
              kind: OpenStackControlPlane
              metadata:
                name: unused
              spec:
                telemetry:
                  template:
                    metricStorage:
                      dashboardsEnabled: true
            target:
              kind: OpenStackControlPlane
