---
- name: "Deploy logging dependencies"
  hosts: "{{ cifmw_target_hook_host | default('localhost')  }}"
  gather_facts: false
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  tasks:
    - name: Deploy logging dependencies
      ansible.builtin.import_role:
        name: deploy-logging-dependencies
    - name: Copy dataplane nodeset kustomization
      ansible.builtin.copy:
        dest: "{{ cifmw_basedir }}/artifacts/manifests/kustomizations/dataplane/90-kustomize-dataplane-logging-service.yaml"
        content: |-
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization
          resources:
          namespace: {{ cifmw_install_yamls_defaults['NAMESPACE'] }}
          patches:
          - target:
              kind: OpenStackDataPlaneNodeSet
              name: .*
            patch: |-
              - op: add
                path: /spec/services/-
                value: logging

    - name: Copy controlplane kustomization
      ansible.builtin.copy:
        dest: "{{ cifmw_basedir }}/artifacts/manifests/kustomizations/controlplane/90-kustomize-controlplane-logging.yaml"
        content: |-
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization
          namespace: openstack
          patches:
          - patch: |-
              apiVersion: core.openstack.org/v1beta1
              kind: OpenStackControlPlane
              metadata:
                name: unused
              spec:
                telemetry:
                  enabled: true
                  template:
                    logging:
                      enabled: true
            target:
              kind: OpenStackControlPlane
