---
- name: "Create the kustomization for increasing rabbitmq replicas"
  hosts: "{{ cifmw_target_hook_host | default('localhost')  }}"
  gather_facts: false
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  tasks:
    - name: Copy controlplane kustomization
      ansible.builtin.copy:
        dest: "{{ cifmw_basedir }}/artifacts/manifests/kustomizations/controlplane/91-kustomize-controlplane-increase-rabbit-replicas.yaml"
        content: |-
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization
          namespace: openstack
          patches:
          - patch: |-
              apiVersion: core.openstack.org/v1beta1
              kind: OpenStackControlPlane
              metadata:
                name: unused
              spec:
                # By increasing the rabbitmq replicas, the CI jobs by default
                # run out of PVs. This storage class will create PVs
                # dynamically, but works only on CRC based environments.
                storageClass: crc-csi-hostpath-provisioner
                rabbitmq:
                  templates:
                    rabbitmq:
                      replicas: 3
            target:
              kind: OpenStackControlPlane
