# The minio sometimes fails to deploy, because of:
# no matches for kind "Route" in version "route.openshift.io/v1" ensure CRDs are installed first
#
# Let's try to check if the route is available in the cluster bofere deploying minio
- name: Wait for the route kind to be present in the cluster
  ansible.builtin.command:
    cmd:
      oc api-resources --api-group=route.openshift.io --no-headers
  delay: 10
  retries: 50
  register: output
  until: output.stdout_lines | length != 0

- name: Create minio deployment
  ansible.builtin.shell:
    cmd: |
      oc apply -f {{ role_path }}/files/minio-dev.yaml

- name: Wait for the minio pod to be created
  ansible.builtin.command:
    cmd:
      oc get pods --namespace=minio-dev minio
  delay: 10
  retries: 20
  register: output
  until: output.stdout_lines | length != 0

- name: Wait for the minio pod to be running
  ansible.builtin.command:
    cmd: |
      oc wait --timeout=300s --for jsonpath="{.status.phase}"=Running --namespace=minio-dev pod minio
