- name: Create the SA and apply the right permissions
  ansible.builtin.shell:
    cmd: |
      oc create sa collector -n openshift-logging
      oc adm policy add-cluster-role-to-user logging-collector-logs-writer -z collector -n openshift-logging
      oc adm policy add-cluster-role-to-user collect-application-logs -z collector -n openshift-logging
      oc adm policy add-cluster-role-to-user collect-audit-logs -z collector -n openshift-logging
      oc adm policy add-cluster-role-to-user collect-infrastructure-logs -z collector -n openshift-logging

- name: Create cluster log forwarder
  ansible.builtin.shell:
    cmd: |
      oc apply -f {{ role_path }}/files/cluster_log_forwarder.yaml -n openshift-logging

- name: Wait for cluster log forwarder to be created
  ansible.builtin.command:
    cmd:
      oc get clusterlogforwarder --namespace=openshift-logging collector
  delay: 10
  retries: 20
  register: output
  until: output.stdout_lines | length != 0

- name: Wait for 2 "True" and 0 "False" conditions in ClusterLogForwarder status
  ansible.builtin.shell:
    cmd: >
      oc get clusterlogforwarder collector -n openshift-logging -o json | jq --raw-output '[
        ([.status.conditions[] | select(.status == "True")] | length),
        ([.status.conditions[] | select(.status == "False")] | length)
      ] | @csv'
  register: clf_condition_counts
  until: clf_condition_counts.stdout == "2,0"
  retries: 20
  delay: 20
  changed_when: false
  check_mode: no
