---
#pluginDir: /tmp/plugins
logLevel: debug
handleErrors: True

transports:
  - name: socket
    config:
      socketaddr: "127.0.0.1:3060"
      type: tcp
    handlers:
      - name: ceilometer-metrics
        config:
          source: tcp
applications:
  - name: prometheus
    config:
      host: 0.0.0.0
      port: 3000
      withTimeStamp: True
