---
- hosts: all
  tasks:
    - name: deploy node_exporter container
      containers.podman.podman_container:
        image: "{{ telemetry_node_exporter_image }}"
        name: node_exporter
        state: present
        recreate: yes
        ports:
        - "9100:9100"

    - name: create systemd service file for node_exporter
      copy:
        dest: "/etc/systemd/system/edpm_node_exporter.service"
        content: |
          [Unit]
          Description=node_exporter container
          Wants=network-online.target
          After=network-online.target
          RequiresMountsFor=%t/containers

          [Service]
          Restart=always
          ExecStart=/usr/bin/podman start node_exporter
          ExecReload=/usr/bin/podman kill --signal HUP node_exporter
          ExecStop=/usr/bin/podman stop node_exporter
          ExecStopPost=/usr/bin/podman stop node_exporter
          SuccessExitStatus=0 137 142 143
          TimeoutStopSec=84
          KillMode=control-group
          Type=forking
          RestartSec=60

          [Install]
          WantedBy=multi-user.target

    - name: restart node_exporter
      become: true
      ansible.builtin.systemd:
        state: restarted
        name: edpm_node_exporter.service
